medconnect/force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Attendee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Attendee__c/fields/Company_Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Institution_Name__c</fullName>
    <label>Company / Institution Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Event_Attendee__c/fields/Medical_Event__c.field-meta.xml
<CustomField>
    <fullName>Medical_Event__c</fullName>
    <label>Medical Event</label>
    <referenceTo>Medical_Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

medconnect/force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Event_Speaker__c/fields/Medical_Event__c.field-meta.xml
<CustomField>
    <fullName>Medical_Event__c</fullName>
    <label>Medical Event</label>
    <referenceTo>Medical_Event__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

medconnect/force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location0</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/fields/Landmark__c.field-meta.xml
<CustomField>
    <fullName>Landmark__c</fullName>
    <label>Landmark</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/Medical_Event__c.object-meta.xml
<CustomObject>
    <label>Medical Event</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Medical Events</relationshipLabel>
    <relationshipName>Medical_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Speaker__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/classes/front/EventDetailsController.cls
public with sharing class EventDetailsController {

    public class EventDetailsWrapper {

        @AuraEnabled
        public List<Speaker__c> speakers;

        @AuraEnabled
        public List<Attendee__c> attendees;

        @AuraEnabled
        public Location__c location;
    }

    @AuraEnabled(cacheable=true)
    public static EventDetailsWrapper getEventRelatedDetails(Id eventId) {

        EventDetailsWrapper result = new EventDetailsWrapper();

        Medical_Event__c eventRecord = [
            SELECT Id, Address__c
            FROM Medical_Event__c
            WHERE Id = :eventId
            LIMIT 1
        ];

        if(eventRecord.Address__c != null){

            result.location = [
                SELECT
                    Id,
                    Name,
                    Street__c,
                    City__c,
                    State__c,
                    Postal_Code__c,
                    Country__c,
                    Landmark__c,
                    Verified__c
                FROM Location__c
                WHERE Id = :eventRecord.Address__c
                LIMIT 1
            ];
        }

        result.speakers = new List<Speaker__c>();

        for(Event_Speaker__c es : [

            SELECT
                Speaker__r.Id,
                Speaker__r.Name,
                Speaker__r.Email__c,
                Speaker__r.Phone__c,
                Speaker__r.Specialization__c

            FROM Event_Speaker__c
            WHERE Medical_Event__c = :eventId
        ]){

            result.speakers.add(es.Speaker__r);
        }

        result.attendees = new List<Attendee__c>();

        for(Event_Attendee__c ea : [

            SELECT
                Attendee__r.Id,
                Attendee__r.Name,
                Attendee__r.Email__c,
                Attendee__r.Phone__c,
                Attendee__r.Company_Institution_Name__c

            FROM Event_Attendee__c
            WHERE Medical_Event__c = :eventId
        ]){

            result.attendees.add(ea.Attendee__r);
        }

        return result;
    }
}