medconnect/force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Attendee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Attendee__c/fields/Company_Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Institution_Name__c</fullName>
    <label>Company / Institution Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Clinic_Organizer__c/Clinic_Organizer__c.object-meta.xml
<CustomObject>
    <label>Clinic Organizer</label>
    <nameField>
        <label>Clinic Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinic Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Clinic_Organizer__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Clinic Organizers</relationshipLabel>
    <relationshipName>Clinic_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Event_Attendee__c/fields/Medical_Event__c.field-meta.xml
<CustomField>
    <fullName>Medical_Event__c</fullName>
    <label>Medical Event</label>
    <referenceTo>Medical_Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

medconnect/force-app/main/default/objects/Event_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

medconnect/force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Event_Speaker__c/fields/Medical_Event__c.field-meta.xml
<CustomField>
    <fullName>Medical_Event__c</fullName>
    <label>Medical Event</label>
    <referenceTo>Medical_Event__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

medconnect/force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location0</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/Medical_Event__c.object-meta.xml
<CustomObject>
    <label>Medical Event</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Medical Events</relationshipLabel>
    <relationshipName>Medical_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizer</label>
    <referenceTo>Clinic_Organizer__c</referenceTo>
    <relationshipLabel>Medical Events</relationshipLabel>
    <relationshipName>Medical_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurring?</label>
    <type>Checkbox</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

medconnect/force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Speaker__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/classes/test/MedConnectTriggerTest.cls
@IsTest
public class MedConnectTriggerTest {

    @TestSetup
    static void setupData() {
        Location__c location = new Location__c(
            Name = 'Clinic Recife',
            Street__c = 'Rua Teste',
            City__c = 'Recife',
            State__c = 'PE',
            Postal_Code__c = '50000000',
            Country__c = 'Brazil',
            Verified__c = true
        );
        insert location;

        Clinic_Organizer__c organizer = new Clinic_Organizer__c(
            Name = 'Organizer Test',
            Email__c = 'organizer@test.com',
            Phone__c = '81999990000',
            Location__c = location.Id
        );
        insert organizer;

        Attendee__c attendee = new Attendee__c(
            Name = 'Attendee Test',
            Email__c = 'attendee@test.com',
            Phone__c = '81999991111',
            Company_Institution_Name__c = 'Test Institution',
            Address__c = location.Id
        );
        insert attendee;

        Speaker__c speaker = new Speaker__c(
            Name = 'Speaker Test',
            Email__c = 'speaker@test.com',
            Phone__c = '81999992222',
            Specialization__c = 'Cardiology'
        );
        insert speaker;

        Medical_Event__c event1 = new Medical_Event__c(
            Event_Name__c = 'Health Talk 1',
            Status__c = 'Published',
            Organizer__c = organizer.Id,
            Start_Date_Time__c = System.now().addDays(2),
            End_Date_Time__c = System.now().addDays(3),
            Max_Seats__c = 10,
            Address__c = location.Id,
            Live__c = true,
            Recurring__c = false,
            Event_Type__c = 'In-Person'
        );
        insert event1;

        Medical_Event__c event2 = new Medical_Event__c(
            Event_Name__c = 'Health Talk 2',
            Status__c = 'Published',
            Organizer__c = organizer.Id,
            Start_Date_Time__c = System.now().addDays(4),
            End_Date_Time__c = System.now().addDays(5),
            Max_Seats__c = 10,
            Address__c = location.Id,
            Live__c = true,
            Recurring__c = false,
            Event_Type__c = 'In-Person'
        );
        insert event2;
    }

    @IsTest
    static void shouldCreateEventAttendeeAndSendEmail() {
        Medical_Event__c eventRecord = [
            SELECT Id
            FROM Medical_Event__c
            WHERE Event_Name__c = 'Health Talk 1'
            LIMIT 1
        ];

        Attendee__c attendee = [
            SELECT Id
            FROM Attendee__c
            LIMIT 1
        ];

        Test.startTest();

        Event_Attendee__c registration = new Event_Attendee__c(
            Medical_Event__c = eventRecord.Id,
            Attendee__c = attendee.Id
        );
        insert registration;

        Test.stopTest();

        Event_Attendee__c insertedRegistration = [
            SELECT Id, Medical_Event__c, Attendee__c
            FROM Event_Attendee__c
            WHERE Id = :registration.Id
        ];

        System.assertNotEquals(null, insertedRegistration.Id);
        System.assertEquals(eventRecord.Id, insertedRegistration.Medical_Event__c);
        System.assertEquals(attendee.Id, insertedRegistration.Attendee__c);
    }

    @IsTest
    static void shouldPreventDuplicateActiveSpeakerBooking() {
        Speaker__c speaker = [
            SELECT Id
            FROM Speaker__c
            LIMIT 1
        ];

        List<Medical_Event__c> events = [
            SELECT Id
            FROM Medical_Event__c
            ORDER BY Event_Name__c ASC
        ];

        Event_Speaker__c firstBooking = new Event_Speaker__c(
            Medical_Event__c = events[0].Id,
            Speaker__c = speaker.Id
        );
        insert firstBooking;

        Test.startTest();

        Boolean errorThrown = false;

        try {
            Event_Speaker__c secondBooking = new Event_Speaker__c(
                Medical_Event__c = events[1].Id,
                Speaker__c = speaker.Id
            );
            insert secondBooking;
        } catch (DmlException e) {
            errorThrown = true;
        }

        Test.stopTest();

        System.assertEquals(true, errorThrown, 'Deveria bloquear speaker duplicado em evento ativo.');
    }
}