medconnect/force-app/main/default/objects/Clinic_Organizer__c/Clinic_Organizer__c.object-meta.xml
<CustomObject>
    <label>Clinic Organizer</label>
    <nameField>
        <label>Clinic Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinic Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Clinic_Organizer__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Clinic Organizers</relationshipLabel>
    <relationshipName>Clinic_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location0</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

medconnect/force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/Medical_Event__c.object-meta.xml
<CustomObject>
    <label>Medical Event</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Medical Events</relationshipLabel>
    <relationshipName>Medical_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizer</label>
    <referenceTo>Clinic_Organizer__c</referenceTo>
    <relationshipLabel>Medical Events</relationshipLabel>
    <relationshipName>Medical_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

medconnect/force-app/main/default/objects/Medical_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

medconnect/force-app/main/default/classes/test/MedicalEventRestServiceTest.cls
@IsTest
public class MedicalEventRestServiceTest {

    @TestSetup
    static void setup() {
        Location__c loc = new Location__c(
            Name = 'Test Location',
            Street__c = 'Street 1',
            City__c = 'City',
            State__c = 'State',
            Country__c = 'Brazil'
        );
        insert loc;

        Clinic_Organizer__c org = new Clinic_Organizer__c(
            Name = 'Test Organizer',
            Email__c = 'test@org.com'
        );
        insert org;

        Medical_Event__c eventLive = new Medical_Event__c(
            Event_Name__c = 'Live Event',
            Live__c = true,
            Start_Date_Time__c = System.now().addDays(1),
            End_Date_Time__c = System.now().addDays(2),
            Address__c = loc.Id,
            Organizer__c = org.Id,
            Status__c = 'Published'
        );
        insert eventLive;

        Medical_Event__c eventPast = new Medical_Event__c(
            Event_Name__c = 'Past Event',
            Live__c = true,
            Start_Date_Time__c = System.now().addDays(-2),
            End_Date_Time__c = System.now().addDays(-1),
            Address__c = loc.Id,
            Organizer__c = org.Id,
            Status__c = 'Completed'
        );
        insert eventPast;

        Medical_Event__c eventNotLive = new Medical_Event__c(
            Event_Name__c = 'Not Live Event',
            Live__c = false,
            Start_Date_Time__c = System.now().addDays(1),
            End_Date_Time__c = System.now().addDays(2),
            Address__c = loc.Id,
            Organizer__c = org.Id,
            Status__c = 'Created'
        );
        insert eventNotLive;
    }

    @IsTest
    static void testGetAllEvents() {
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/medical-events/';
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response = new RestResponse();

        Test.startTest();
        MedicalEventRestService.doGet();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
        List<MedicalEventRestService.MedicalEventResponse> response = 
            (List<MedicalEventRestService.MedicalEventResponse>) JSON.deserialize(
                RestContext.response.responseBody.toString(), 
                List<MedicalEventRestService.MedicalEventResponse>.class
            );
        
        System.assertEquals(1, response.size(), 'Deve retornar apenas 1 evento (Live e Futuro)');
        System.assertEquals('Live Event', response[0].name);
    }

    @IsTest
    static void testGetEventById() {
        Medical_Event__c event = [SELECT Id FROM Medical_Event__c WHERE Event_Name__c = 'Live Event' LIMIT 1];
        
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/medical-events/' + event.Id;
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response = new RestResponse();

        Test.startTest();
        MedicalEventRestService.doGet();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
        MedicalEventRestService.MedicalEventResponse response = 
            (MedicalEventRestService.MedicalEventResponse) JSON.deserialize(
                RestContext.response.responseBody.toString(), 
                MedicalEventRestService.MedicalEventResponse.class
            );
        
        System.assertEquals('Live Event', response.name);
    }

    @IsTest
    static void testGetEventNotFound() {
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/medical-events/a00000000000000AAA';
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response = new RestResponse();

        Test.startTest();
        MedicalEventRestService.doGet();
        Test.stopTest();

        System.assertEquals(404, RestContext.response.statusCode);
    }
}