medconnect/force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

medconnect/force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

medconnect/force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

medconnect/force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

medconnect/force-app/main/default/classes/ErrorLogService.cls
public class ErrorLogService {

    public static void logError(Datetime logDateTime, String logDetails, String processName) {
        
        try {
            Error_Log__c log = new Error_Log__c();

            log.Log_Date_Time__c = logDateTime;
            log.Log_Details__c = logDetails;
            log.Process_Name__c = processName;

            insert log;

        } catch (Exception e) {
            System.debug('Erro ao salvar log: ' + e.getMessage());
        }
    }
}